// GETS
const GET_PRODUCTS = 'GET_PRODUCTS';
const GET_PRODUCTS_DETAILS = 'GET_PRODUCTS_DETAILS';

// CATEGORIES
const GET_CATEGORIES = 'GET_CATEGORIES';



// SETEADORES DE ESTADO 
const SET_PAGE = "SET_PAGE";
const SET_CATEGORY = "SET_CATEGORY";

// ORDER

module.exports = {
    GET_PRODUCTS,
    GET_PRODUCTS_DETAILS,
    GET_CATEGORIES,
    SET_PAGE,
    SET_CATEGORY,
}